[package]
name = "wg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
etherparse = "0.15.0"
parking_lot = "0.12.3"
socket2 = "0.5.7"
tun-tap = "0.1.4"

[[bin]]
name = "wg"
path = "src/wg.rs"
