[package]
name = "wg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.3"
libc = "0.2.155"
log = "0.4.22"
nix = { version = "0.29.0", features = ["fs", "poll"] }
parking_lot = "0.12.3"

